#!/bin/bash
./verifier 0.5 ./vda317b/vda317b.block ./vda317b/vda317b.nets output.txt
# ./verifier 0.5 ./ami49/ami49.block ./ami49/ami49.nets output.txt
# ./verifier 0.5 ./ami33/ami33.block ./ami33/ami33.nets output.txt
# ./verifier 0.5 ./test/test.block ./test/test.nets output.txt